module FooterHelper
  def footer_nav_destination_items
    [
      {title: 'Africa', url: 'africa'},
      {title: 'Antarctica', url: 'antarctica'},
      {title: 'Asia', url: 'asia'},
      {title: 'Caribbean Islands', url: 'caribbean'},
      {title: 'Central America', url: 'central-america'},
      {title: 'Europe', url: 'europe'},
      {title: 'Middle East', url: 'middle-east'},
      {title: 'North America', url: 'north-america'},
      {title: 'Pacific', url: 'pacific'},
      {title: 'South America', url: 'south-america'}
    ]
  end

  def footer_nav_shop_items
    [
      {title: 'Destination guides', url: 'destination-guides'},
      {title: 'eBooks', url: 'ebooks'},
      {title: 'Pictorial & gifts', url: 'pictorials-and-gifts'},
      {title: 'Phrasebooks', url: 'phrasebooks'},
      {title: 'Lonely Planet Kids', url: 'childrens-books'},
      {title: 'Special offers', url: 'special-offers'}
    ]
  end

  def footer_nav_thorntree_items
    [
      {title: 'Country forums', url: 'categories/country-forums'},
      {title: 'Talk to Lonely Planet', url: 'categories/talk-to-lonely-planet'},
      {title: 'Interest forums', url: 'categories/interest-forums'},
      {title: 'Travel buddies & for sale', url: 'categories/sell-swap-meet-up'}
    ]
  end

  def footer_nav_interests_items
    [
      {title:'Adventure travel', url:'adventure-travel'},
      {title:'Beaches', url:'beaches'},
      {title:'Budget travel', url:'budget-travel'},
      {title:'Family travel', url:'family-travel'},
      {title:'Festivals and events', url:'festivals-and-events'},
      {title:'Food and drink', url:'food-and-drink'},
      {title:'Honeymoons and romance', url:'honeymoons-and-romance'},
      {title:'Luxury travel', url:'luxury-travel'},
      {title:'Round the world travel', url:'round-the-world-travel'},
      {title:'Wildlife and nature', url:'wildlife-and-nature'}
    ]
  end

  def footer_nav_travel_bookings_items
    [
      {title: 'Hotels', url: 'hotels'},
      {title: 'Flights', url: 'flights'},
      {title: 'Insurance', url: 'travel-insurance'}
    ]
  end

  def social_media_nav
    [
      {title: 'twitter', url: 'https://twitter.com/lonelyplanet'},
      {title: 'facebook', url: 'https://www.facebook.com/lonelyplanet'},
      {title: 'google-plus', url: 'https://plus.google.com/+LonelyPlanet/'},
      {title: 'flickr', url: 'http://www.flickr.com/groups/lonelyplanetpublications/'},
      {title: 'youtube', url: 'http://www.youtube.com/user/LonelyPlanet'},
      {title: 'pinterest', url: 'http://pinterest.com/lonelyplanet/'},
      {title: 'instagram', url: 'http://instagram.com/lonelyplanet'},
      {title: 'vine', url: 'https://vine.co/lonelyplanet'},
      {title: 'article', url: '/blog'}
    ]
  end

  def footer_nav_about_items
    [
      {title: 'About us', url: '/about/'},
      {title: 'Work for us', url: '/jobs/'},
      {title: 'Contact us', url: '/contact/'},
      {title: 'Press, trade &amp; advertising', url: '/press-trade-advertising/'},
      {title: 'Terms &amp; conditions', url: '/legal/website-terms/'},
      {title: 'Privacy policy', url: '/legal/privacy-policy/'}
    ]
  end

  def language_options
    [
      ["www.lonelyplanet.com", "English"],
      ["www.lonelyplanet.in", "English (India)"],
      ["www.lonelyplanet.de", "Deutsch"],
      ["www.lonelyplanet.fr", "Fran&#231;ais"],
      ["www.lonelyplanet.es", "Espa&#241;ol"],
      ["www.lonelyplanetitalia.it", "Italiano"],
      ["www.lonelyplanet.ru", "&#x420;&#x443;&#x441;&#x441;&#x43A;&#x438;&#x439;"],
      ["www.lonelyplanetbrasil.com.br", "Portugu&ecirc;s"],
      ["www.lonelyplanet.cz", "&#268;esky"],
      ["www.lonelyplanet.co.kr", "&#xD55C;&#xAD6D;&#xC5B4;"]
    ]
  end

  def footer_newsletter_country_items
    [
      {title: "Australia"},
      {title: "United Kingdom"},
      {title: "United States"},
      {title: "Afghanistan"},
      {title: "Aland Islands"},
      {title: "Albania"},
      {title: "Algeria"},
      {title: "American Samoa"},
      {title: "Andorra"},
      {title: "Angola"},
      {title: "Anguilla"},
      {title: "Antarctica"},
      {title: "Antigua And Barbuda"},
      {title: "Argentina"},
      {title: "Armenia"},
      {title: "Aruba"},
      {title: "Austria"},
      {title: "Azerbaijan"},
      {title: "Bahamas"},
      {title: "Bahrain"},
      {title: "Bangladesh"},
      {title: "Barbados"},
      {title: "Belarus"},
      {title: "Belgium"},
      {title: "Belize"},
      {title: "Benin"},
      {title: "Bermuda"},
      {title: "Bhutan"},
      {title: "Bolivia"},
      {title: "Bonaire"},
      {title: "Bosnia and Herzegovina"},
      {title: "Botswana"},
      {title: "Bouvet Island"},
      {title: "Brazil"},
      {title: "British Indian Ocean Territory"},
      {title: "British Virgin Islands"},
      {title: "Brunei Darussalam"},
      {title: "Bulgaria"},
      {title: "Burkina Faso"},
      {title: "Burundi"},
      {title: "Cambodia"},
      {title: "Cameroon"},
      {title: "Canada"},
      {title: "Cape Verde"},
      {title: "Cayman Islands"},
      {title: "Central African Republic"},
      {title: "Chad"},
      {title: "Channel Islands, The"},
      {title: "Chile"},
      {title: "China"},
      {title: "Christmas Island"},
      {title: "Cocos (Keeling) Islands"},
      {title: "Colombia"},
      {title: "Comoros"},
      {title: "Congo"},
      {title: "Congo, The Democratic Republic of the"},
      {title: "Cook Islands"},
      {title: "Costa Rica"},
      {title: "Cote D'Ivoire"},
      {title: "Croatia"},
      {title: "Cuba"},
      {title: "Curacao"},
      {title: "Cyprus"},
      {title: "Czech Republic"},
      {title: "Denmark"},
      {title: "Djibouti"},
      {title: "Dominica"},
      {title: "Dominican Republic"},
      {title: "East Timor"},
      {title: "Ecuador"},
      {title: "Egypt"},
      {title: "El Salvador"},
      {title: "England"},
      {title: "Equatorial Guinea"},
      {title: "Eritrea"},
      {title: "Estonia"},
      {title: "Ethiopia"},
      {title: "Falkland Islands (Malvinas)"},
      {title: "Faroe Islands"},
      {title: "Fiji"},
      {title: "Finland"},
      {title: "France"},
      {title: "French Guiana"},
      {title: "French Polynesia"},
      {title: "French Southern Territories"},
      {title: "Gabon"},
      {title: "Gambia"},
      {title: "Georgia"},
      {title: "Germany"},
      {title: "Ghana"},
      {title: "Gibraltar"},
      {title: "Greece"},
      {title: "Greenland"},
      {title: "Grenada"},
      {title: "Guadeloupe"},
      {title: "Guam"},
      {title: "Guatemala"},
      {title: "Guernsey"},
      {title: "Guinea"},
      {title: "Guinea-Bissau"},
      {title: "Guyana"},
      {title: "Haiti"},
      {title: "Heard Island And Mcdonald Islands"},
      {title: "Holy See (Vatican City State)"},
      {title: "Honduras"},
      {title: "Hong Kong"},
      {title: "Hungary"},
      {title: "Iceland"},
      {title: "India"},
      {title: "Indonesia"},
      {title: "Iran, Islamic Republic of"},
      {title: "Iraq"},
      {title: "Ireland"},
      {title: "Isle of Man"},
      {title: "Israel"},
      {title: "Italy"},
      {title: "Jamaica"},
      {title: "Japan"},
      {title: "Jersey"},
      {title: "Jordan"},
      {title: "Kazakhstan"},
      {title: "Kenya"},
      {title: "Kiribati"},
      {title: "Korea, Democratic People's Republic of"},
      {title: "Korea, Republic of"},
      {title: "Kuwait"},
      {title: "Kyrgyzstan"},
      {title: "Lao People's Democratic Republic"},
      {title: "Latvia"},
      {title: "Lebanon"},
      {title: "Lesotho"},
      {title: "Liberia"},
      {title: "Libyan Arab Jamahiriya"},
      {title: "Liechtenstein"},
      {title: "Lithuania"},
      {title: "Luxembourg"},
      {title: "Macao"},
      {title: "Macedonia, The Former Yugoslav Republic of"},
      {title: "Madagascar"},
      {title: "Malawi"},
      {title: "Malaysia"},
      {title: "Maldives"},
      {title: "Mali"},
      {title: "Malta"},
      {title: "Marshall Islands"},
      {title: "Martinique"},
      {title: "Mauritania"},
      {title: "Mauritius"},
      {title: "Mayotte"},
      {title: "Mexico"},
      {title: "Micronesia, Federated States of"},
      {title: "Moldova, Republic of"},
      {title: "Monaco"},
      {title: "Mongolia"},
      {title: "Montenegro"},
      {title: "Montserrat"},
      {title: "Morocco"},
      {title: "Mozambique"},
      {title: "Myanmar"},
      {title: "Namibia"},
      {title: "Nauru"},
      {title: "Nepal"},
      {title: "Netherlands Antilles"},
      {title: "Netherlands"},
      {title: "New Caledonia"},
      {title: "New Guinea"},
      {title: "New Zealand"},
      {title: "Nicaragua"},
      {title: "Niger"},
      {title: "Nigeria"},
      {title: "Niue"},
      {title: "Norfolk Island"},
      {title: "North Korea"},
      {title: "Northern Ireland"},
      {title: "Northern Mariana Islands"},
      {title: "Norway"},
      {title: "Oman"},
      {title: "Pakistan"},
      {title: "Palau"},
      {title: "Palestinian Territory, Occupied"},
      {title: "Panama"},
      {title: "Papua New Guinea"},
      {title: "Paraguay"},
      {title: "Peru"},
      {title: "Philippines"},
      {title: "Pitcairn"},
      {title: "Poland"},
      {title: "Portugal"},
      {title: "Puerto Rico"},
      {title: "Qatar"},
      {title: "Reunion"},
      {title: "Romania"},
      {title: "Russian Federation"},
      {title: "Rwanda"},
      {title: "Saba"},
      {title: "Saint Eustatius"},
      {title: "Saint Barthelemy"},
      {title: "Saint Helena"},
      {title: "Saint Kitts and Nevis"},
      {title: "Saint Lucia"},
      {title: "Saint Martin (France)"},
      {title: "Saint Pierre and Miquelon"},
      {title: "Saint Vincent and the Grenadines"},
      {title: "Samoa"},
      {title: "San Marino"},
      {title: "Sao Tome and Principe"},
      {title: "Saudi Arabia"},
      {title: "Scotland"},
      {title: "Senegal"},
      {title: "Serbia"},
      {title: "Seychelles"},
      {title: "Sierra Leone"},
      {title: "Singapore"},
      {title: "Slovakia"},
      {title: "Slovenia"},
      {title: "Solomon Islands"},
      {title: "Somalia"},
      {title: "South Africa"},
      {title: "South Korea"},
      {title: "South Georgia and the South Sandwich Islands"},
      {title: "Spain"},
      {title: "Sri Lanka"},
      {title: "Sudan"},
      {title: "Suriname"},
      {title: "Svalbard and Jan Mayen"},
      {title: "Swaziland"},
      {title: "Sweden"},
      {title: "Switzerland"},
      {title: "Syrian Arab Republic"},
      {title: "Taiwan"},
      {title: "Tajikistan"},
      {title: "Tanzania, United Republic of"},
      {title: "Thailand"},
      {title: "Timor-Leste"},
      {title: "Togo"},
      {title: "Tokelau"},
      {title: "Tonga"},
      {title: "Trinidad and Tobago"},
      {title: "Tunisia"},
      {title: "Turkey"},
      {title: "Turkmenistan"},
      {title: "Turks and Caicos Islands"},
      {title: "Tuvalu"},
      {title: "Uganda"},
      {title: "Ukraine"},
      {title: "United Arab Emirates"},
      {title: "United States Minor Outlying Islands"},
      {title: "Uruguay"},
      {title: "Uzbekistan"},
      {title: "Vanuatu"},
      {title: "Venezuela"},
      {title: "Viet Nam"},
      {title: "Virgin Islands, British"},
      {title: "Virgin Islands, U.S."},
      {title: "Wallis and Futuna"},
      {title: "Western Sahara"},
      {title: "Yemen"},
      {title: "Zaire"},
      {title: "Zambia"},
      {title: "Zimbabwe"}
    ]
  end

end
