module WidgetHelper
  def travel_country_options
    [
      {title: "USA", value: "USA"},
      {title: "United Kingdom", value: "GBR"},
      {title: "Australia", value: "AUS"},
      {title: "Canada", value: "CAN"},
      {title: "-----------------------", disabled: true},
      {title: "Andorra", value: "AND"},
      {title: "Antarctica", value: "ANT"},
      {title: "Argentina", value: "ARG"},
      {title: "Armenia", value: "ARM"},
      {title: "Aruba", value: "ABW"},
      {title: "Austria", value: "AUT"},
      {title: "Azerbaijan", value: "AZE"},
      {title: "Bahamas", value: "BHS"},
      {title: "Bahrain", value: "BHR"},
      {title: "Bangladesh", value: "BGD"},
      {title: "Barbados", value: "BRB"},
      {title: "Belarus", value: "BLR"},
      {title: "Belgium", value: "BEL"},
      {title: "Belize", value: "BLZ"},
      {title: "Bermuda", value: "BMU"},
      {title: "Bhutan", value: "BTN"},
      {title: "Bolivia", value: "BOL"},
      {title: "Bonaire, Saint Eustatius and Saba", value: "BES"},
      {title: "Bosnia", value: "BIH"},
      {title: "Botswana", value: "BWA"},
      {title: "Brazil", value: "BRA"},
      {title: "Brunei Darussalam", value: "BRN"},
      {title: "Bulgaria", value: "BGR"},
      {title: "Cambodia", value: "KHM"},
      {title: "Cameroon", value: "CMR"},
      {title: "Cayman Islands", value: "CYM"},
      {title: "Chile", value: "CHL"},
      {title: "China", value: "CHN"},
      {title: "Colombia", value: "COL"},
      {title: "Costa Rica", value: "CRI"},
      {title: "Croatia", value: "HRV"},
      {title: "Cuba", value: "CUB"},
      {title: "Cura?ao", value: "CUW"},
      {title: "Cyprus", value: "CYP"},
      {title: "Czech Republic", value: "CZE"},
      {title: "Denmark", value: "DNK"},
      {title: "Domninican Republic", value: "DOM"},
      {title: "Ecuador", value: "ECU"},
      {title: "Egypt", value: "EGY"},
      {title: "El Salvador", value: "SLV"},
      {title: "Estonia", value: "EST"},
      {title: "Falkland Islands", value: "FLK"},
      {title: "Fiji", value: "FJI"},
      {title: "Finland", value: "FIN"},
      {title: "France", value: "FRA"},
      {title: "French Polynesia", value: "PYF"},
      {title: "Georgia", value: "GEO"},
      {title: "Germany", value: "DEU"},
      {title: "Gibraltar", value: "GIB"},
      {title: "Greece", value: "GRC"},
      {title: "Greenland", value: "GRL"},
      {title: "Guadeloupe", value: "GLP"},
      {title: "Guam", value: "GUM"},
      {title: "Guatemala", value: "GTM"},
      {title: "Honduras", value: "HND"},
      {title: "Hong Kong", value: "HKG"},
      {title: "Hungary", value: "HUN"},
      {title: "Iceland", value: "ISL"},
      {title: "India", value: "IND"},
      {title: "Indonesia", value: "IDN"},
      {title: "Iran", value: "IRN"},
      {title: "Ireland", value: "IRL"},
      {title: "Israel", value: "ISR"},
      {title: "Italy", value: "ITA"},
      {title: "Jamaica", value: "JAM"},
      {title: "Japan", value: "JPN"},
      {title: "Kazakhstan", value: "KAZ"},
      {title: "Kenya", value: "KEN"},
      {title: "Kuwait", value: "KWT"},
      {title: "Kyrgyzstan", value: "KGZ"},
      {title: "Laos", value: "LAO"},
      {title: "Latvia", value: "LVA"},
      {title: "Liechtenstein", value: "LIE"},
      {title: "Lithuania", value: "LTU"},
      {title: "Luxembourg", value: "LUX"},
      {title: "Macau", value: "MAC"},
      {title: "Macedonia", value: "MKD"},
      {title: "Madagascar", value: "MDG"},
      {title: "Malaysia", value: "MYS"},
      {title: "Maldives", value: "MDV"},
      {title: "Malta", value: "MLT"},
      {title: "Mauritius", value: "MUS"},
      {title: "Mexico", value: "MEX"},
      {title: "Moldova", value: "MDA"},
      {title: "Monaco", value: "MCO"},
      {title: "Mongolia", value: "MNG"},
      {title: "Morrocco", value: "MAR"},
      {title: "Nepal", value: "NPL"},
      {title: "Netherlands", value: "NLD"},
      {title: "New Caledonia", value: "NCL"},
      {title: "New Zealand", value: "NZL"},
      {title: "Nicaragua", value: "NIC"},
      {title: "Norway", value: "NOR"},
      {title: "Oman", value: "OMN"},
      {title: "Pakistan", value: "PAK"},
      {title: "Palau", value: "PLW"},
      {title: "Panama", value: "PAN"},
      {title: "Papua New Guinea", value: "PNG"},
      {title: "Paraguay", value: "PRY"},
      {title: "Peru", value: "PER"},
      {title: "Philippines", value: "PHL"},
      {title: "Poland", value: "POL"},
      {title: "Portugal", value: "PRT"},
      {title: "Puerto Rico", value: "PRI"},
      {title: "Qatar", value: "QAT"},
      {title: "Romania", value: "ROU"},
      {title: "Russia", value: "RUS"},
      {title: "Samoa", value: "WSM"},
      {title: "San Marino", value: "SMR"},
      {title: "Saudi Arabia", value: "SAU"},
      {title: "Singapore", value: "SGP"},
      {title: "Sint Maarten", value: "SXM"},
      {title: "Slovakia", value: "SVK"},
      {title: "Slovenia", value: "SVN"},
      {title: "Solomon Islands", value: "SLB"},
      {title: "South Africa", value: "ZAF"},
      {title: "South Korea", value: "KOR"},
      {title: "Spain", value: "ESP"},
      {title: "Sri Lanka", value: "LKA"},
      {title: "Sweden", value: "SWE"},
      {title: "Switzerland", value: "CHE"},
      {title: "Taiwan", value: "TWN"},
      {title: "Tajikistan", value: "TJK"},
      {title: "Thailand", value: "THA"},
      {title: "Tonga", value: "TON"},
      {title: "Trinidad and Tobago", value: "TTO"},
      {title: "Tunisia", value: "TUN"},
      {title: "Turkey", value: "TUR"},
      {title: "Turkmenistan", value: "TKM"},
      {title: "Ukraine", value: "UKR"},
      {title: "United Arab Emirates", value: "ARE"},
      {title: "Uruguay", value: "URY"},
      {title: "Uzbekistan", value: "UZB"},
      {title: "Vanuatu", value: "VUT"},
      {title: "Venezuela", value: "VEN"},
      {title: "Vietnam", value: "VNM"},
      {title: "Virgin Islands (British)", value: "VGB"}
    ]
  end

  def travel_duration_options
    [
      {title: "2 days", value: "2d"},
      {title: "3 days", value: "3d"},
      {title: "5 days", value: "5d"},
      {title: "1 week", value: "1w"},
      {title: "2 weeks", value: "2w"},
      {title: "3 weeks", value: "3w"},
      {title: "4 weeks", value: "4w"},
      {title: "5 weeks", value: "5w"},
      {title: "6 weeks", value: "6w"},
      {title: "7 weeks", value: "7w"},
      {title: "2 months", value: "2m"},
      {title: "3 months", value: "3m"},
      {title: "4 months", value: "4m"},
      {title: "5 months", value: "5m"},
      {title: "6 months", value: "6m"},
      {title: "7 months", value: "7m"},
      {title: "8 months", value: "8m"},
      {title: "9 months", value: "9m"},
      {title: "10 months", value: "10m"},
      {title: "11 months", value: "11m"},
      {title: "12 months", value: "12m"}
    ]
  end

  def car_rental_time_options
    [
      {title: "00:00"},
      {title: "00:30"},
      {title: "01:00"},
      {title: "01:30"},
      {title: "02:00"},
      {title: "02:30"},
      {title: "03:00"},
      {title: "03:30"},
      {title: "04:00"},
      {title: "04:30"},
      {title: "05:00"},
      {title: "05:30"},
      {title: "06:00"},
      {title: "06:30"},
      {title: "07:00"},
      {title: "07:30"},
      {title: "08:00"},
      {title: "08:30"},
      {title: "09:00"},
      {title: "09:30"},
      {title: "10:00"},
      {title: "10:30"},
      {title: "11:00"},
      {title: "11:30"},
      {title: "12:00"},
      {title: "12:30"},
      {title: "13:00"},
      {title: "13:30"},
      {title: "14:00"},
      {title: "14:30"},
      {title: "15:00"},
      {title: "15:30"},
      {title: "16:00"},
      {title: "16:30"},
      {title: "17:00"},
      {title: "17:30"},
      {title: "18:00"},
      {title: "18:30"},
      {title: "19:00"},
      {title: "19:30"},
      {title: "20:00"},
      {title: "20:30"},
      {title: "21:00"},
      {title: "21:30"},
      {title: "22:00"},
      {title: "22:30"},
      {title: "23:00"},
      {title: "23:30"}
    ]
  end

  def car_rental_country_options
    [
      {title: "USA"},
      {title: "UK"}
    ]
  end

  def car_rental_currency_options
    [
      {title: "USD"},
      {title: "GBP"}
    ]
  end
end
